FROM php:8.2-apache

# Ativa mod_rewrite
RUN a2enmod rewrite

# Copia os arquivos do projeto
COPY . /var/www/html/

# Permissões para o JSON (edição)
RUN chown -R www-data:www-data /var/www/html \
    && chmod 664 /var/www/html/registros_chamadas.json

EXPOSE 80
